// Code generated by the Encore v1.56.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = typeof window !== 'undefined' ? window.location.origin : "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-ai-ielts-app-ybri.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the ai-ielts-app-ybri Encore application.
 */
export default class Client {
    public readonly agents: agents.ServiceClient
    public readonly frontend: frontend.ServiceClient
    public readonly ielts: ielts.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.agents = new agents.ServiceClient(base)
        this.frontend = new frontend.ServiceClient(base)
        this.ielts = new ielts.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: auth.AuthParams | AuthDataGenerator
}

export namespace agents {
    export interface BatchFeedbackRequest {
        feedbacks: FeedbackRequest[]
    }

    export interface BatchFeedbackResponse {
        results: {
            index: number
            status: "success" | "error"
            feedback?: FeedbackResponse
            error?: string
        }[]
        total: number
        successful: number
        failed: number
    }

    export interface FeedbackRequest {
        passage: string
        question: string
        questionType: string
        correctAnswer: string
        studentAnswer: string
    }

    export interface FeedbackRequest {
        passage: string
        question: string
        questionType: string
        correctAnswer: string
        studentAnswer: string
    }

    export interface FeedbackResponse {
        "is_correct": boolean
        feedback: string
        reasoning: string
        "strategy_tip": string
        "passage_reference": string
        confidence?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.checkAIFeedbackHealth = this.checkAIFeedbackHealth.bind(this)
            this.getReadingAIFeedback = this.getReadingAIFeedback.bind(this)
            this.getReadingAIFeedbackBatch = this.getReadingAIFeedbackBatch.bind(this)
            this.submitReadingWithAIFeedback = this.submitReadingWithAIFeedback.bind(this)
        }

        /**
         * Check if the AI Feedback service is healthy and responsive.
         * 
         * @example
         * const health = await backend.ielts.checkAIFeedbackHealth();
         * console.log(`Service status: ${health.status}`);
         */
        public async checkAIFeedbackHealth(): Promise<{
            status: string
            version: string
            model: string
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading/ai-feedback/health`)
            return await resp.json() as {
                status: string
                version: string
                model: string
            }
        }

        /**
         * Get AI-powered feedback for a single IELTS Reading answer.
         * 
         * This endpoint calls the Python LangChain feedback service and returns
         * intelligent, educational feedback based on the passage content.
         * 
         * @example
         * const feedback = await backend.ielts.getReadingAIFeedback({
         * passage: "The Industrial Revolution...",
         * question: "When did it begin?",
         * questionType: "Short Answer Questions",
         * correctAnswer: "late 18th century",
         * studentAnswer: "late 1700s"
         * });
         */
        public async getReadingAIFeedback(params: FeedbackRequest): Promise<FeedbackResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/ai-feedback`, JSON.stringify(params))
            return await resp.json() as FeedbackResponse
        }

        /**
         * Get AI-powered feedback for multiple IELTS Reading answers.
         * 
         * Useful for processing a complete test (up to 40 questions) at once.
         * 
         * @example
         * const batchResult = await backend.ielts.getReadingAIFeedbackBatch({
         * feedbacks: [
         * { passage: "...", question: "...", ... },
         * { passage: "...", question: "...", ... },
         * ]
         * });
         */
        public async getReadingAIFeedbackBatch(params: BatchFeedbackRequest): Promise<BatchFeedbackResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/ai-feedback/batch`, JSON.stringify(params))
            return await resp.json() as BatchFeedbackResponse
        }

        /**
         * Enhanced version of submitReading that includes AI feedback.
         * 
         * This extends your existing submitReading endpoint to automatically
         * generate AI feedback for each incorrect answer.
         */
        public async submitReadingWithAIFeedback(params: {
            testId: number
            passageId: number
            answers: { [key: number]: string }
        }): Promise<{
            score: number
            totalQuestions: number
            correctAnswers: number
            results: {
                questionId: number
                isCorrect: boolean
                correctAnswer: string
                studentAnswer: string
                aiFeedback?: FeedbackResponse
            }[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/submit-with-ai`, JSON.stringify(params))
            return await resp.json() as {
                score: number
                totalQuestions: number
                correctAnswers: number
                results: {
                    questionId: number
                    isCorrect: boolean
                    correctAnswer: string
                    studentAnswer: string
                    aiFeedback?: FeedbackResponse
                }[]
            }
        }
    }
}

export namespace auth {
    export interface AuthParams {
        authorization: string
    }
}

export namespace frontend {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.assets = this.assets.bind(this)
        }

        public async assets(path: string[]): Promise<void> {
            await this.baseClient.callTypedAPI("HEAD", `/frontend/${path.map(encodeURIComponent).join("/")}`)
        }
    }
}

export namespace ielts {
    export interface AddToVocabularyRequest {
        userId: string
        text: string
        definition: string
        translation: string
        targetLanguage: string
        exampleSentence: string
        topic?: string
    }

    export interface AdvancedTip {
        title: string
        description: string
        application?: string
    }

    export interface AttitudeIndicatorEntry {
        words?: string[]
        example?: string
    }

    export interface AttitudeIndicators {
        positive?: AttitudeIndicatorEntry
        negative?: AttitudeIndicatorEntry
        neutral?: AttitudeIndicatorEntry
        cautious?: AttitudeIndicatorEntry
        certain?: AttitudeIndicatorEntry
        critical?: AttitudeIndicatorEntry
    }

    export interface CreateHighlightRequest {
        userId: string
        passageTitle: string
        highlightedText: string
        startPosition: number
        endPosition: number
        highlightType: string
        highlightColor?: string
    }

    export interface CreateUserRequest {
        id: string
        name: string
        targetBand: number
        examDate?: string
        language?: string
        theme?: string
    }

    export interface DailyGoal {
        goalDate: string
        targetMinutes: number
        completedMinutes: number
        activitiesCompleted: number
        targetActivities: number
    }

    export interface DeeperFeedbackResponse {
        verdict: string
        correctAnswer: string
        whyStudentIsWrong: {
            reason: string
            studentMistakePattern: string
        }
        evidence: {
            quote: string
            analysis: string
        }
        strategyTip: {
            name: string
            steps: string[]
        }
        personalizedAdvice: string
    }

    export interface DifficultyExamples {
        easy?: {
            characteristics?: string
            example?: DifficultyQAExample
        }
        medium?: {
            characteristics?: string
            example?: DifficultyQAExample
        }
        hard?: {
            characteristics?: string
            example?: DifficultyQAExample
        }
    }

    export interface DifficultyQAExample {
        passage: string
        question: string
        options: string[]
        correctAnswer: string
        whyEasy?: string
        whyMedium?: string
        whyHard?: string
    }

    export interface DosAndDonts {
        dos?: string[]
        donts?: string[]
    }

    export interface EmergencyStrategy {
        whenRunningOutOfTime?: string[]
        "guessing Strategy"?: string[]
        confidenceBooster?: string
    }

    export interface EssayAnalysisRequest {
        essay: string
        taskType: number
        userId: string
    }

    export interface EssayAnalysisResponse {
        overallScore: number
        taskResponse: number
        coherenceCohesion: number
        lexicalResource: number
        grammaticalRange: number
        feedback: string
        suggestions: string[]
    }

    export interface FlowChartConnection {
        from: string
        to: string
        label?: string
        style?: "solid" | "dashed"
    }

    export interface FlowChartNode {
        id: string
        type: "stage" | "gap" | "decision"
        content?: string
        gapNumber?: number
        correctAnswer?: string
        position?: number
    }

    export interface FlowChartStructure {
        title: string
        orientation: "vertical" | "horizontal"
        nodes: FlowChartNode[]
        connections: FlowChartConnection[]
    }

    export type KeyTechniques = { [key: string]: string }

    export interface LearningPath {
        phase1?: LearningPathPhase
        phase2?: LearningPathPhase
        phase3?: LearningPathPhase
        phase4?: LearningPathPhase
    }

    export interface LearningPathPhase {
        name?: string
        focus?: string[]
        duration?: string
        sections?: string[]
    }

    export interface ListeningQuestion {
        id: number
        type: "multiple-choice" | "fill-in-blank" | "matching" | "pick-two"
        questionNumber: number
        question: string
        options?: string[]
        correctAnswer: string | string[]
        alternativeAnswers?: string[]
        explanation?: string
    }

    export interface ListeningResult {
        id: number
        score: number
        totalQuestions: number
        correctAnswers: { [key: number]: string | string[] }
        userAnswers: { [key: number]: string }
        explanations: { [key: number]: string }
        bandScore: number
    }

    export interface ListeningSession {
        id: number
        testId: number
        testTitle: string
        score: number
        totalQuestions: number
        bandScore: number
        timeTaken?: number
        createdAt: string
    }

    export interface ListeningSubmission {
        userId: string
        testId: number
        userAnswers: { [key: number]: string }
        timeTaken?: number
    }

    export interface ListeningTest {
        id: number
        title: string
        section: number
        difficulty: "easy" | "medium" | "hard"
        audioFile: string
        duration: number
        instructions?: string
        transcript?: ListeningTranscriptLine[]
        transcripts?: ListeningTranscriptSection[]
        questions: ListeningQuestion[]
    }

    export interface ListeningTestMeta {
        id: number
        title: string
        section: number
        difficulty: string
        questionCount: number
        duration: number
    }

    export interface ListeningTranscriptLine {
        speaker: string
        timestamp?: string
        text: string
    }

    export interface ListeningTranscriptSection {
        title: string
        lines: ListeningTranscriptLine[]
    }

    export interface MCQuestionTypeEntry {
        type: string
        difficulty?: string
        signals?: string[]
        whatToLookFor?: string
        strategy?: string
    }

    export interface ModuleCollection {
        category: string
        modules: StruggleModule[]
    }

    export interface MultipleAnswerExample {
        passage?: string
        question?: string
        options?: string[]
        correctAnswers?: string[]
        thinkingProcess?: string
        eliminationProcess?: { [key: string]: string }
        explanation?: string
        commonMistake?: string
    }

    export interface MultipleAnswerQuestions {
        scoringRule?: string
        howToRecognize?: string
        strategy?: string[]
        example?: MultipleAnswerExample
    }

    export interface ParaphrasingPattern {
        type: string
        passageExample?: string
        optionExamples?: string[]
        tip?: string
    }

    export interface ParaphrasingPatterns {
        description?: string
        commonPatterns?: ParaphrasingPattern[]
    }

    export interface PassageParagraph {
        id: string
        text: string
    }

    export interface PracticalQuiz {
        passage?: { [key: string]: string }
        headings?: string[]
        questions: PracticalQuizQuestion[]
        miniPractice?: {
            paragraph: string
            headings: string[]
            correctAnswer: string
            explanation?: string
        }
    }

    export interface PracticalQuizQuestion {
        id: number
        type: "matching-headings" | "true-false-not-given" | "multiple-choice" | "short-answer" | "gap-fill"
        text: string
        options?: string[]
        correctAnswer: string | string[]
        explanation?: string
    }

    export interface ProgressOverview {
        overall: UserProgress[]
        weeklyActivity: number
        studyStreak: number
        totalPracticeTime: number
    }

    export interface ProgressSummary {
        percent: number
        totals: {
            planned: number
            completed: number
            points: {
                easy: number
                medium: number
                hard: number
            }
        }
    }

    export interface ProxyChatMessage {
        role: "user" | "assistant" | "system"
        content: string
    }

    export interface ProxyChatRequest {
        userId: string
        session_id: string
        messages: ProxyChatMessage[]
        dropped_question_id?: string | null
    }

    export interface ProxyTrainingStartRequest {
        userId: string
        session_id: string
        skill: string
        student_id: string
        accuracy: number
        total_attempted: number
        correct: number
        recent_errors: any[]
    }

    export interface ProxyTrainingStartResponse {
        session_id: string
        first_message: string
    }

    export interface QuickRecognition {
        identifiers?: string[]
        variants?: string[]
    }

    export interface QuickStartGuide {
        title?: string
        essentials?: string[]
        commonTrap?: string
    }

    export interface ReadingHighlight {
        id: number
        highlightedText: string
        startPosition: number
        endPosition: number
        highlightType: string
        highlightColor: string
        createdAt: string
    }

    export interface ReadingPassage {
        id: number
        title: string
        content: string
        paragraphs: PassageParagraph[]
        questions: ReadingQuestionGroup[]
        level: string
        estimatedTime: number
        createdAt?: string
    }

    export interface ReadingPassage {
        id: number
        title: string
        content: string
        paragraphs: PassageParagraph[]
        questions: ReadingQuestionGroup[]
        level: string
        estimatedTime: number
        createdAt?: string
    }

    export interface ReadingQuestion {
        id: number
        type?: string
        questionText: string
        options?: string[]
        correctAnswer: string | string[]
        explanation?: string
        answerType?: "single" | "multiple"
        "gap_number"?: number
        context?: string
        "evidence_quote"?: string
        "evidence_location"?: string
        "answer_type"?: string | "adjective" | "number" | "date"
    }

    export interface ReadingQuestionGroup {
        id: number
        type: "matching-headings" | "true-false-not-given" | "gap-fill" | "multiple-choice" | "short-answer" | "sentence-completion" | "matching-features" | "summary-completion" | "note-completion" | "table-completion" | "flow-chart-completion" | "matching-information" | "matching-sentence-endings"
        title: string
        instructions: string
        questions: ReadingQuestion[]
        "completion_type"?: "summary" | "notes" | "table" | "flow-chart"
        "word_limit"?: string
        structure?: string
        "sentence_beginnings"?: string[]
        "sentence_endings"?: {
            letter: string
            text: string
        }[]
        "flow_chart"?: FlowChartStructure
    }

    export interface ReadingResult {
        id: number
        score: number
        totalQuestions: number
        correctAnswers: { [key: number]: string }
        explanations: { [key: number]: string }
    }

    export interface ReadingSession {
        id: number
        passageTitle: string
        score: number
        totalQuestions: number
        timeTaken?: number
        createdAt: string
    }

    export interface ReadingSkill {
        type: string
        total: number
        correct: number
        accuracy: number
    }

    export interface ReadingSubmission {
        userId: string
        passageTitle: string
        passageContent: string
        questions: ReadingQuestion[]
        userAnswers: { [key: number]: string }
        timeTaken?: number
    }

    export interface ReadingTestMeta {
        testId: number
        testName: string
        totalQuestions: number
    }

    export interface ReadingTestResponse {
        testId: number
        testName: string
        passages: ReadingPassage[]
    }

    export interface SpeakingFeedback {
        id: number
        bandScore: number
        fluencyScore: number
        grammarScore: number
        pronunciationScore: number
        coherenceScore: number
        feedback: string
        transcription?: string
    }

    export interface SpeakingQuestion {
        part: number
        question: string
    }

    export interface SpeakingSession {
        id: number
        part: number
        question: string
        transcription?: string
        audioUrl?: string
        bandScore?: number
        fluencyScore?: number
        grammarScore?: number
        pronunciationScore?: number
        coherenceScore?: number
        feedback?: string
        createdAt: string
    }

    export interface SpeakingSubmission {
        userId: string
        part: number
        question: string
        transcription?: string
        audioUrl?: string
    }

    export interface StrategyTip {
        step: number
        title: string
        description: string
    }

    export interface StruggleModule {
        moduleId: string
        moduleName: string
        targetQuestionTypes: string[]
        triggerConditions: {
            mistakePatterns: string[]
            contextKeywords: string[]
        }
        content: {
            explanation: string
            visualExample: {
                passage: string
                statement: string
                analysis: string
            }
            checkpointQuestions: string[]
        }
        officialSource: string
    }

    export interface SubtleDifferenceExample {
        passage: string
        question: string
        optionA: string
        optionB: string
        correctAnswer: string
        keyDifference: string
        explanation: string
    }

    export interface SubtleDifferences {
        description?: string
        example1?: SubtleDifferenceExample
        example2?: SubtleDifferenceExample
        example3?: SubtleDifferenceExample
    }

    export type SummaryRange = "daily" | "weekly" | "monthly"

    export interface Task {
        id: string
        userId: string
        name: string
        category: TaskCategory
        difficulty: TaskDifficulty
        status: "planned" | "in_progress" | "completed"
        estimatedMinutes: number
        progress: number
        dueAt?: string
        createdAt: string
        updatedAt: string
        completedAt?: string | null
    }

    export type TaskCategory = "reading" | "writing" | "speaking" | "listening" | "vocabulary" | "grammar"

    export type TaskDifficulty = "easy" | "medium" | "hard"

    export interface TaskSuggestion {
        name: string
        category: TaskCategory
        difficulty: TaskDifficulty
        estimatedMinutes: number
        dueAt?: string
    }

    export interface TheoryContent {
        id: string
        name: string
        category: string
        whatIsIt: TheoryWhatIsIt
        example: TheoryExample
        commonMistakes: TheoryMistake[]
        strategyTips: StrategyTip[]
        timeManagement: TimeManagement
        quiz?: TheoryQuiz
        theoryQuiz?: TheoryQuiz
        practicalQuiz?: PracticalQuiz
        scoring?: TheoryScoring
        /**
         * Optional extended fields for Multiple Choice theory
         */
        frequency?: string

        quickStartGuide?: QuickStartGuide
        learningPath?: LearningPath
        quickRecognition?: QuickRecognition
        questionTypes?: MCQuestionTypeEntry[]
        attitudeIndicators?: AttitudeIndicators
        paraphrasingPatterns?: ParaphrasingPatterns
        examples?: WorkedExamples
        multipleAnswerQuestions?: MultipleAnswerQuestions
        subtleDifferences?: SubtleDifferences
        difficultyExamples?: DifficultyExamples
        trapPatterns?: TrapPattern[]
        warningSign?: string
        dosAndDonts?: DosAndDonts
        advancedTips?: AdvancedTip[]
        emergencyStrategy?: EmergencyStrategy
        keyTechniques?: KeyTechniques
    }

    export interface TheoryExample {
        passage: string | { [key: string]: string }
        headings?: string[]
        questions: TheoryExampleQuestion[]
    }

    export interface TheoryExampleQuestion {
        id: number
        text: string
        options?: string[]
        correctAnswer: string
        explanation: string
    }

    export interface TheoryListItem {
        id: string
        name: string
        category: string
    }

    export interface TheoryMistake {
        title: string
        description: string
        example?: any
        qualifyingWords?: {
            absolute?: string[]
            qualified?: string[]
            caution?: string
        }
        howToAvoid?: string
    }

    export interface TheoryQuiz {
        passage?: string
        questions: TheoryQuizQuestion[]
    }

    export interface TheoryQuizQuestion {
        id: number
        type: TheoryQuizQuestionType
        text: string
        options?: string[]
        correctAnswer: string | string[]
        explanation?: string
    }

    export type TheoryQuizQuestionType = "true-false-not-given" | "multiple-choice" | "matching-headings" | "short-answer" | "gap-fill"

    export interface TheoryScoring {
        excellent?: {
            range: string
            message: string
        }
        good?: {
            range: string
            message: string
        }
        needsReview?: {
            range: string
            message: string
        }
        needsStudy?: {
            range: string
            message: string
        }
    }

    export interface TheoryWhatIsIt {
        description: string
        skillTested: string
    }

    export interface TimeManagement {
        timePerQuestion: string
        tip: string
        timePerMultipleAnswer?: string
        totalTime?: string
        allocation?: {
            reading?: string
            analyzing?: string
            deciding?: string
        }
    }

    export interface TranslationRequest {
        text: string
        targetLanguage: string
    }

    export interface TranslationResponse {
        originalText: string
        translatedText: string
        targetLanguage: string
        definition?: string
        exampleSentence?: string
        audioUrl?: string
    }

    export interface TrapPattern {
        type: string
        description?: string
        example?: string
        redFlag?: string
    }

    export interface UpdateUserRequest {
        name?: string
        targetBand?: number
        examDate?: string
        language?: string
        theme?: string
    }

    export interface User {
        id: string
        name: string
        targetBand: number
        examDate?: string
        language: string
        theme: string
        plan: string
        essaysUsed: number
        activeAnalysis: boolean
        readingCreditsUsed: number
        createdAt: string
        updatedAt: string
    }

    export interface UserProgress {
        skill: string
        estimatedBand?: number
        practiceCount: number
        lastPracticeDate?: string
    }

    export interface VocabularyProgress {
        totalWords: number
        knownWords: number
        learningWords: number
        reviewWords: number
    }

    export interface VocabularyResponse {
        examples: string[]
        synonyms: string[]
        collocations: string[]
        difficulty: string
    }

    export interface VocabularyWord {
        id: number
        word: string
        definition: string
        exampleSentence: string
        topic: string
        difficultyLevel: number
        audioUrl?: string
        status?: string
        nextReviewDate?: string
        reviewCount?: number
    }

    export interface WorkedExample {
        difficulty?: string
        passage?: string
        question?: string
        options?: string[]
        correctAnswer?: string
        thinkingProcess?: string
        eliminationProcess?: { [key: string]: string }
        explanation?: string
        attitudeClues?: string[]
    }

    export interface WorkedExamples {
        detailQuestion?: WorkedExample
        inferenceQuestion?: WorkedExample
        opinionQuestion?: WorkedExample
        purposeQuestion?: WorkedExample
    }

    export interface WritingFeedback {
        id: number
        bandScore: number
        grammarFeedback: string
        vocabularyFeedback: string
        structureFeedback: string
        coherenceFeedback: string
    }

    export interface WritingPrompt {
        taskType: number
        prompt: string
        chartMetadata?: string
    }

    export interface WritingSession {
        id: number
        taskType: number
        prompt: string
        content: string
        bandScore?: number
        grammarFeedback?: string
        vocabularyFeedback?: string
        structureFeedback?: string
        coherenceFeedback?: string
        createdAt: string
    }

    export interface WritingSubmission {
        userId: string
        taskType: number
        prompt: string
        content: string
        bandScore?: number
        grammarFeedback?: string
        vocabularyFeedback?: string
        structureFeedback?: string
        coherenceFeedback?: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.acceptTaskSuggestions = this.acceptTaskSuggestions.bind(this)
            this.addToVocabulary = this.addToVocabulary.bind(this)
            this.analyzeEssay = this.analyzeEssay.bind(this)
            this.checkAndLockEssay = this.checkAndLockEssay.bind(this)
            this.completeEssayAnalysis = this.completeEssayAnalysis.bind(this)
            this.createHighlight = this.createHighlight.bind(this)
            this.createReadingPassage = this.createReadingPassage.bind(this)
            this.createTask = this.createTask.bind(this)
            this.createUser = this.createUser.bind(this)
            this.deleteHighlight = this.deleteHighlight.bind(this)
            this.deleteTask = this.deleteTask.bind(this)
            this.generateTaskSuggestions = this.generateTaskSuggestions.bind(this)
            this.getDailyGoal = this.getDailyGoal.bind(this)
            this.getEssayLimits = this.getEssayLimits.bind(this)
            this.getHighlights = this.getHighlights.bind(this)
            this.getLatestReadingSession = this.getLatestReadingSession.bind(this)
            this.getListeningAudio = this.getListeningAudio.bind(this)
            this.getListeningSessions = this.getListeningSessions.bind(this)
            this.getListeningTest = this.getListeningTest.bind(this)
            this.getListeningTests = this.getListeningTests.bind(this)
            this.getListeningTranscript = this.getListeningTranscript.bind(this)
            this.getProgress = this.getProgress.bind(this)
            this.getProgressSummary = this.getProgressSummary.bind(this)
            this.getReadingDeeperFeedback = this.getReadingDeeperFeedback.bind(this)
            this.getReadingPassage = this.getReadingPassage.bind(this)
            this.getReadingPassageById = this.getReadingPassageById.bind(this)
            this.getReadingPassages = this.getReadingPassages.bind(this)
            this.getReadingSessions = this.getReadingSessions.bind(this)
            this.getReadingSkills = this.getReadingSkills.bind(this)
            this.getReadingTestById = this.getReadingTestById.bind(this)
            this.getReadingTests = this.getReadingTests.bind(this)
            this.getReadingTheoryById = this.getReadingTheoryById.bind(this)
            this.getReadingTheoryList = this.getReadingTheoryList.bind(this)
            this.getSpeakingQuestion = this.getSpeakingQuestion.bind(this)
            this.getSpeakingSessions = this.getSpeakingSessions.bind(this)
            this.getStruggleModules = this.getStruggleModules.bind(this)
            this.getUser = this.getUser.bind(this)
            this.getVocabularyEnhancement = this.getVocabularyEnhancement.bind(this)
            this.getVocabularyProgress = this.getVocabularyProgress.bind(this)
            this.getVocabularyTopics = this.getVocabularyTopics.bind(this)
            this.getVocabularyWords = this.getVocabularyWords.bind(this)
            this.getWritingPrompt = this.getWritingPrompt.bind(this)
            this.getWritingSessionById = this.getWritingSessionById.bind(this)
            this.getWritingSessions = this.getWritingSessions.bind(this)
            this.listTasks = this.listTasks.bind(this)
            this.submitListening = this.submitListening.bind(this)
            this.submitReading = this.submitReading.bind(this)
            this.submitSpeaking = this.submitSpeaking.bind(this)
            this.submitWriting = this.submitWriting.bind(this)
            this.translateText = this.translateText.bind(this)
            this.updateDailyGoal = this.updateDailyGoal.bind(this)
            this.updateProgress = this.updateProgress.bind(this)
            this.updateTask = this.updateTask.bind(this)
            this.updateUser = this.updateUser.bind(this)
            this.updateVocabularyStatus = this.updateVocabularyStatus.bind(this)
            this.proxyReadingChat = this.proxyReadingChat.bind(this)
            this.proxyTrainingStart = this.proxyTrainingStart.bind(this)
            this.proxyReadingFeedback = this.proxyReadingFeedback.bind(this)
        }

        /**
         * POST /progress/ai/accept
         */
        public async acceptTaskSuggestions(params: {
            userId: string
            suggestions: TaskSuggestion[]
        }): Promise<{
            tasks: Task[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/progress/ai/accept`, JSON.stringify(params))
            return await resp.json() as {
                tasks: Task[]
            }
        }

        /**
         * Adds highlighted text to user's vocabulary.
         */
        public async addToVocabulary(params: AddToVocabularyRequest): Promise<{
            /**
             * Adds highlighted text to user's vocabulary.
             */
            success: boolean

            /**
             * Adds highlighted text to user's vocabulary.
             */
            wordId: number
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/add-to-vocabulary`, JSON.stringify(params))
            return await resp.json() as {
                /**
                 * Adds highlighted text to user's vocabulary.
                 */
                success: boolean

                /**
                 * Adds highlighted text to user's vocabulary.
                 */
                wordId: number
            }
        }

        /**
         * Essay Analysis with LangChain
         */
        public async analyzeEssay(params: EssayAnalysisRequest): Promise<EssayAnalysisResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/ai/analyze-essay`, JSON.stringify(params))
            return await resp.json() as EssayAnalysisResponse
        }

        /**
         * Atomically checks the essay limit and locks the user for analysis.
         * Uses auth.userID — the URL has no :id parameter to prevent spoofing.
         */
        public async checkAndLockEssay(): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/essay-limits/check-and-lock`)
        }

        /**
         * Unlocks the user after analysis. Increments essay credit only on success.
         */
        public async completeEssayAnalysis(params: {
            /**
             * Unlocks the user after analysis. Increments essay credit only on success.
             */
            success: boolean
        }): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/essay-limits/complete`, JSON.stringify(params))
        }

        /**
         * Creates a new highlight for a reading passage.
         */
        public async createHighlight(params: CreateHighlightRequest): Promise<ReadingHighlight> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/highlights`, JSON.stringify(params))
            return await resp.json() as ReadingHighlight
        }

        /**
         * API endpoint to create a new reading passage
         */
        public async createReadingPassage(params: ReadingPassage): Promise<{
            /**
             * API endpoint to create a new reading passage
             */
            id: number
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/passages`, JSON.stringify(params))
            return await resp.json() as {
                /**
                 * API endpoint to create a new reading passage
                 */
                id: number
            }
        }

        /**
         * POST /progress/tasks
         */
        public async createTask(params: {
            userId: string
            name: string
            category: TaskCategory
            difficulty: TaskDifficulty
            estimatedMinutes?: number
            dueAt?: string
        }): Promise<Task> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/progress/tasks`, JSON.stringify(params))
            return await resp.json() as Task
        }

        /**
         * Creates a new user profile.
         */
        public async createUser(params: CreateUserRequest): Promise<User> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/users`, JSON.stringify(params))
            return await resp.json() as User
        }

        /**
         * Deletes a highlight.
         */
        public async deleteHighlight(userId: string, highlightId: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/users/${encodeURIComponent(userId)}/reading/highlights/delete/${encodeURIComponent(highlightId)}`)
        }

        /**
         * DELETE /progress/tasks/:id
         */
        public async deleteTask(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/progress/tasks/${encodeURIComponent(id)}`)
        }

        /**
         * POST /progress/ai/generate
         */
        public async generateTaskSuggestions(params: {
            userId: string
            range: SummaryRange
            timeAvailableMinutes: number
            targetBand?: number
        }): Promise<{
            suggestions: TaskSuggestion[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/progress/ai/generate`, JSON.stringify(params))
            return await resp.json() as {
                suggestions: TaskSuggestion[]
            }
        }

        /**
         * Retrieves today's daily goal for a user.
         */
        public async getDailyGoal(userId: string): Promise<DailyGoal> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/daily-goal`)
            return await resp.json() as DailyGoal
        }

        /**
         * Returns the current essay usage and plan limits for a user.
         */
        public async getEssayLimits(id: string): Promise<{
            plan: string
            essaysUsed: number
            limit: number
            remaining: number
            activeAnalysis: boolean
            readingCreditsUsed: number
            readingCreditsLimit: number
            readingCreditsRemaining: number
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(id)}/essay-limits`)
            return await resp.json() as {
                plan: string
                essaysUsed: number
                limit: number
                remaining: number
                activeAnalysis: boolean
                readingCreditsUsed: number
                readingCreditsLimit: number
                readingCreditsRemaining: number
            }
        }

        /**
         * Retrieves highlights for a specific passage and user.
         */
        public async getHighlights(userId: string, passageTitle: string): Promise<{
            /**
             * Retrieves highlights for a specific passage and user.
             */
            highlights: ReadingHighlight[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/reading/highlights/${encodeURIComponent(passageTitle)}`)
            return await resp.json() as {
                /**
                 * Retrieves highlights for a specific passage and user.
                 */
                highlights: ReadingHighlight[]
            }
        }

        /**
         * Retrieves the latest reading session for a specific test and passage.
         */
        public async getLatestReadingSession(userId: string, params: {
            testId: number
            passageId: number
        }): Promise<{
            id: number
            userId: string
            testId: number
            passageId: number
            userAnswers: { [key: number]: string }
            correctAnswers: { [key: number]: string }
            score: number
            totalQuestions: number
            createdAt: string
        }> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                passageId: String(params.passageId),
                testId: String(params.testId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/reading/sessions/latest`, undefined, { query })
            return await resp.json() as {
                id: number
                userId: string
                testId: number
                passageId: number
                userAnswers: { [key: number]: string }
                correctAnswers: { [key: number]: string }
                score: number
                totalQuestions: number
                createdAt: string
            }
        }

        /**
         * Legacy endpoint for backward compatibility
         */
        public async getListeningAudio(): Promise<ListeningTest> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/listening/audio`)
            return await resp.json() as ListeningTest
        }

        /**
         * Get user's listening session history
         */
        public async getListeningSessions(userId: string): Promise<{
            /**
             * Get user's listening session history
             */
            sessions: ListeningSession[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/listening/sessions`)
            return await resp.json() as {
                /**
                 * Get user's listening session history
                 */
                sessions: ListeningSession[]
            }
        }

        /**
         * Get a specific listening test by ID (without correct answers for practice)
         */
        public async getListeningTest(testId: number): Promise<ListeningTest> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/listening/tests/${encodeURIComponent(testId)}`)
            return await resp.json() as ListeningTest
        }

        /**
         * Get list of all available listening tests
         */
        public async getListeningTests(): Promise<{
            /**
             * Get list of all available listening tests
             */
            tests: ListeningTestMeta[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/listening/tests`)
            return await resp.json() as {
                /**
                 * Get list of all available listening tests
                 */
                tests: ListeningTestMeta[]
            }
        }

        /**
         * Get transcript for a test (can be shown after submission or during practice based on settings)
         */
        public async getListeningTranscript(testId: number): Promise<{
            /**
             * Get transcript for a test (can be shown after submission or during practice based on settings)
             */
            transcript: ListeningTranscriptLine[]

            /**
             * Get transcript for a test (can be shown after submission or during practice based on settings)
             */
            transcripts?: ListeningTranscriptSection[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/listening/tests/${encodeURIComponent(testId)}/transcript`)
            return await resp.json() as {
                /**
                 * Get transcript for a test (can be shown after submission or during practice based on settings)
                 */
                transcript: ListeningTranscriptLine[]

                /**
                 * Get transcript for a test (can be shown after submission or during practice based on settings)
                 */
                transcripts?: ListeningTranscriptSection[]
            }
        }

        /**
         * Retrieves user progress overview.
         */
        public async getProgress(userId: string): Promise<ProgressOverview> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/progress`)
            return await resp.json() as ProgressOverview
        }

        /**
         * GET /progress/summary
         */
        public async getProgressSummary(params: {
            userId: string
            range?: SummaryRange
        }): Promise<ProgressSummary> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                range: params.range === undefined ? undefined : String(params.range),
                userId: params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/progress/summary`, undefined, { query })
            return await resp.json() as ProgressSummary
        }

        /**
         * Get deeper AI feedback for a specific question
         */
        public async getReadingDeeperFeedback(params: {
            userId: string
            testId: number
            passageId: number
            questionId: number
        }): Promise<DeeperFeedbackResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/deeper-feedback`, JSON.stringify(params))
            return await resp.json() as DeeperFeedbackResponse
        }

        /**
         * Proxies chat messages to the AI Tutor.
         */
        public async proxyReadingChat(params: ProxyChatRequest): Promise<ProxyChatMessage> {
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/chat`, JSON.stringify(params))
            return await resp.json() as ProxyChatMessage
        }

        /**
         * Proxies training start requests.
         */
        public async proxyTrainingStart(params: ProxyTrainingStartRequest): Promise<ProxyTrainingStartResponse> {
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/training/start`, JSON.stringify(params))
            return await resp.json() as ProxyTrainingStartResponse
        }

        /**
         * Proxies deeper feedback requests.
         */
        public async proxyReadingFeedback(params: {
            userId: string;
            passage: string;
            question: string;
            question_type: string;
            correct_answer: string;
            student_answer: string;
        }): Promise<DeeperFeedbackResponse> {
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/feedback`, JSON.stringify(params))
            return await resp.json() as DeeperFeedbackResponse
        }

        /**
         * Retrieves a random reading passage with questions.
         */
        public async getReadingPassage(): Promise<ReadingPassage> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading/passage`)
            return await resp.json() as ReadingPassage
        }

        /**
         * API endpoint to get a specific reading passage by ID
         */
        public async getReadingPassageById(id: number): Promise<ReadingPassage> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading/passages/${encodeURIComponent(id)}`)
            return await resp.json() as ReadingPassage
        }

        /**
         * API endpoint to get all reading passages
         */
        public async getReadingPassages(): Promise<{
            /**
             * API endpoint to get all reading passages
             */
            passages: ReadingPassage[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading/passages`)
            return await resp.json() as {
                /**
                 * API endpoint to get all reading passages
                 */
                passages: ReadingPassage[]
            }
        }

        /**
         * Retrieves user's reading session history.
         */
        public async getReadingSessions(userId: string): Promise<{
            /**
             * Retrieves user's reading session history.
             */
            sessions: ReadingSession[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/reading/sessions`)
            return await resp.json() as {
                /**
                 * Retrieves user's reading session history.
                 */
                sessions: ReadingSession[]
            }
        }

        /**
         * Retrieves aggregated reading skills data.
         */
        public async getReadingSkills(userId: string): Promise<{
            /**
             * Retrieves aggregated reading skills data.
             */
            skills: ReadingSkill[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/reading/skills`)
            return await resp.json() as {
                /**
                 * Retrieves aggregated reading skills data.
                 */
                skills: ReadingSkill[]
            }
        }

        /**
         * NEW: Get passages for a specific test
         */
        public async getReadingTestById(testId: number): Promise<ReadingTestResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading/tests/${encodeURIComponent(testId)}`)
            return await resp.json() as ReadingTestResponse
        }

        /**
         * NEW: Get list of all tests
         */
        public async getReadingTests(): Promise<{
            /**
             * NEW: Get list of all tests
             */
            tests: ReadingTestMeta[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading/tests`)
            return await resp.json() as {
                /**
                 * NEW: Get list of all tests
                 */
                tests: ReadingTestMeta[]
            }
        }

        /**
         * NEW: Get theory content for a specific question type
         */
        public async getReadingTheoryById(questionType: string): Promise<TheoryContent> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading/theory/${encodeURIComponent(questionType)}`)
            return await resp.json() as TheoryContent
        }

        /**
         * NEW: Get list of all theory question types
         */
        public async getReadingTheoryList(): Promise<{
            /**
             * NEW: Get list of all theory question types
             */
            theories: TheoryListItem[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading/theory`)
            return await resp.json() as {
                /**
                 * NEW: Get list of all theory question types
                 */
                theories: TheoryListItem[]
            }
        }

        /**
         * Retrieves a random speaking question for a specific part.
         */
        public async getSpeakingQuestion(part: number): Promise<SpeakingQuestion> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/speaking/question/${encodeURIComponent(part)}`)
            return await resp.json() as SpeakingQuestion
        }

        /**
         * Retrieves user's speaking session history.
         */
        public async getSpeakingSessions(userId: string): Promise<{
            /**
             * Retrieves user's speaking session history.
             */
            sessions: SpeakingSession[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/speaking/sessions`)
            return await resp.json() as {
                /**
                 * Retrieves user's speaking session history.
                 */
                sessions: SpeakingSession[]
            }
        }

        /**
         * NEW: Get all struggle modules
         */
        public async getStruggleModules(): Promise<{
            /**
             * NEW: Get all struggle modules
             */
            modules: { [key: string]: ModuleCollection }
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading/struggle-modules`)
            return await resp.json() as {
                /**
                 * NEW: Get all struggle modules
                 */
                modules: { [key: string]: ModuleCollection }
            }
        }

        /**
         * Retrieves a user by ID.
         */
        public async getUser(id: string): Promise<User> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(id)}`)
            return await resp.json() as User
        }

        /**
         * Enhanced Vocabulary with LangChain
         */
        public async getVocabularyEnhancement(word: string): Promise<VocabularyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/ai/vocabulary/${encodeURIComponent(word)}/enhance`)
            return await resp.json() as VocabularyResponse
        }

        /**
         * Retrieves vocabulary progress for a user.
         */
        public async getVocabularyProgress(userId: string): Promise<VocabularyProgress> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/vocabulary/progress`)
            return await resp.json() as VocabularyProgress
        }

        /**
         * Retrieves vocabulary topics.
         */
        public async getVocabularyTopics(): Promise<{
            /**
             * Retrieves vocabulary topics.
             */
            topics: string[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/vocabulary/topics`)
            return await resp.json() as {
                /**
                 * Retrieves vocabulary topics.
                 */
                topics: string[]
            }
        }

        /**
         * Retrieves vocabulary words for practice.
         */
        public async getVocabularyWords(userId: string, params: {
            /**
             * Retrieves vocabulary words for practice.
             */
            topic?: string

            /**
             * Retrieves vocabulary words for practice.
             */
            limit?: number
        }): Promise<{
            /**
             * Retrieves vocabulary words for practice.
             */
            words: VocabularyWord[]
        }> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                topic: params.topic,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/vocabulary`, undefined, { query })
            return await resp.json() as {
                /**
                 * Retrieves vocabulary words for practice.
                 */
                words: VocabularyWord[]
            }
        }

        /**
         * Retrieves a random writing prompt for a specific task type.
         */
        public async getWritingPrompt(taskType: number, params: {
            /**
             * Retrieves a random writing prompt for a specific task type.
             */
            "test_id"?: number
        }): Promise<WritingPrompt> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "test_id": params["test_id"] === undefined ? undefined : String(params["test_id"]),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/writing/prompt/${encodeURIComponent(taskType)}`, undefined, { query })
            return await resp.json() as WritingPrompt
        }

        public async getWritingSessionById(id: number): Promise<{
            session: WritingSession | null
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/writing/sessions/${encodeURIComponent(id)}`)
            return await resp.json() as {
                session: WritingSession | null
            }
        }

        /**
         * Retrieves user's writing session history.
         */
        public async getWritingSessions(userId: string): Promise<{
            /**
             * Retrieves user's writing session history.
             */
            sessions: WritingSession[]
        }> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/users/${encodeURIComponent(userId)}/writing/sessions`)
            return await resp.json() as {
                /**
                 * Retrieves user's writing session history.
                 */
                sessions: WritingSession[]
            }
        }

        /**
         * GET /progress/tasks
         */
        public async listTasks(params: {
            userId: string
            range?: "daily" | "weekly" | "monthly"
            status?: "all" | "planned" | "in-progress" | "completed"
        }): Promise<{
            tasks: Task[]
        }> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                range: params.range === undefined ? undefined : String(params.range),
                status: params.status === undefined ? undefined : String(params.status),
                userId: params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/progress/tasks`, undefined, { query })
            return await resp.json() as {
                tasks: Task[]
            }
        }

        /**
         * Submit listening answers for evaluation
         */
        public async submitListening(params: ListeningSubmission): Promise<ListeningResult> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/listening/submit`, JSON.stringify(params))
            return await resp.json() as ListeningResult
        }

        /**
         * Submits reading answers for evaluation.
         */
        public async submitReading(params: ReadingSubmission): Promise<ReadingResult> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/submit`, JSON.stringify(params))
            return await resp.json() as ReadingResult
        }

        /**
         * Submits a speaking response for evaluation.
         */
        public async submitSpeaking(params: SpeakingSubmission): Promise<SpeakingFeedback> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/speaking/submit`, JSON.stringify(params))
            return await resp.json() as SpeakingFeedback
        }

        /**
         * Submits writing answers for evaluation.
         */
        public async submitWriting(params: WritingSubmission): Promise<WritingFeedback> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/writing/submit`, JSON.stringify(params))
            return await resp.json() as WritingFeedback
        }

        /**
         * Translates text to the target language.
         */
        public async translateText(params: TranslationRequest): Promise<TranslationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/translate`, JSON.stringify(params))
            return await resp.json() as TranslationResponse
        }

        /**
         * Updates daily goal progress.
         */
        public async updateDailyGoal(userId: string, params: {
            /**
             * Updates daily goal progress.
             */
            minutesCompleted: number

            /**
             * Updates daily goal progress.
             */
            activitiesCompleted: number
        }): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/users/${encodeURIComponent(userId)}/daily-goal/update`, JSON.stringify(params))
        }

        /**
         * Updates user progress for a specific skill.
         */
        public async updateProgress(userId: string, skill: string, params: {
            /**
             * Updates user progress for a specific skill.
             */
            estimatedBand?: number
        }): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/users/${encodeURIComponent(userId)}/progress/${encodeURIComponent(skill)}`, JSON.stringify(params))
        }

        /**
         * PATCH /progress/tasks/:id
         */
        public async updateTask(id: string, params: {
            progress?: number
            status?: "planned" | "in-progress" | "completed"
            completedAt?: string
        }): Promise<Task> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/progress/tasks/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Task
        }

        /**
         * Updates a user profile.
         */
        public async updateUser(id: string, params: UpdateUserRequest): Promise<User> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/users/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as User
        }

        /**
         * Updates user's vocabulary word status.
         */
        public async updateVocabularyStatus(userId: string, wordId: number, params: {
            /**
             * Updates user's vocabulary word status.
             */
            status: string
        }): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/users/${encodeURIComponent(userId)}/vocabulary/${encodeURIComponent(wordId)}/status`, JSON.stringify(params))
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ? parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
        .replaceAll("=", "")
        .replaceAll("+", "-")
        .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
    | auth.AuthParams
    | Promise<auth.AuthParams | undefined>
    | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "ai-ielts-app-ybri-Generated-TS-Client (Encore/v1.56.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: auth.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = { ...query, ...authData.query };
            }
            if (authData.headers) {
                headers = { ...headers, ...authData.headers };
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = { ...query, ...authData.query };
            }
            if (authData.headers) {
                headers = { ...headers, ...authData.headers };
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = { ...query, ...authData.query };
            }
            if (authData.headers) {
                headers = { ...headers, ...authData.headers };
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = { ...this.headers, ...init.headers, ...headers }

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = { ...query, ...authData.query };
            }
            if (authData.headers) {
                init.headers = { ...init.headers, ...authData.headers };
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL + path + queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof (err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof (err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value: 'APIError',
            enumerable: false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
