
import React, { useState, useEffect } from "react";
import { FeedbackSummaryView } from "./FeedbackSummaryView";
import { FeedbackDeepDiveView } from "./FeedbackDeepDiveView";
import { EvaluationResult, CoachingResult, Criterion } from "@/types/writing-feedback";
import { ArrowUpRight } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface FeedbackContainerProps {
    evaluation: EvaluationResult;
    coaching: CoachingResult;
    essay: string;
    taskType: "task1" | "task2";
}

export function FeedbackContainer({ evaluation, coaching, essay, taskType }: FeedbackContainerProps) {
    const [viewMode, setViewMode] = useState<"summary" | "deep-dive">("summary");
    const [activeCriterion, setActiveCriterion] = useState<Criterion | null>(null);

    // Scroll to top when view changes
    useEffect(() => {
        window.scrollTo({ top: 0, behavior: "smooth" });
    }, [viewMode]);

    const handleCriterionClick = (criterion: Criterion) => {
        setActiveCriterion(criterion);
        setViewMode("deep-dive");
    };

    const handleBackToSummary = () => {
        setViewMode("summary");
        setActiveCriterion(null);
    };

    return (
        <div className="w-full flex-1 flex flex-col bg-[#0F172A] text-slate-100">
            {/* Disclaimer Banner */}
            <div className="bg-indigo-950/30 border-b border-indigo-900/50 py-2 px-4 text-center">
                <p className="text-xs text-indigo-200 flex items-center justify-center gap-2">
                    <span className="bg-indigo-500/20 text-indigo-300 px-1.5 py-0.5 rounded text-[10px] font-bold tracking-wider uppercase">
                        AI Beta
                    </span>
                    Feedback is generated by AI and may vary from official IELTS examiners.
                    <a href="#" className="underline hover:text-white flex items-center gap-0.5">
                        Learn more <ArrowUpRight className="w-3 h-3" />
                    </a>
                </p>
            </div>

            <main className="flex-1 flex flex-col relative overflow-hidden">
                <AnimatePresence mode="wait">
                    {viewMode === "summary" ? (
                        <motion.div
                            key="summary"
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: -20 }}
                            transition={{ duration: 0.3, ease: "easeInOut" }}
                            className="w-full max-w-5xl mx-auto py-12 px-4"
                        >
                            <FeedbackSummaryView
                                evaluation={evaluation}
                                taskType={taskType}
                                onCriterionClick={handleCriterionClick}
                            />
                        </motion.div>
                    ) : (
                        <motion.div
                            key="deep-dive"
                            initial={{ opacity: 0, x: 20 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: 20 }}
                            transition={{ duration: 0.3, ease: "easeInOut" }}
                            className="flex-1 h-full"
                        >
                            <FeedbackDeepDiveView
                                essay={essay}
                                evaluation={evaluation}
                                coaching={coaching}
                                activeCriterion={activeCriterion}
                                onBack={handleBackToSummary}
                                onCriterionChange={setActiveCriterion}
                            />
                        </motion.div>
                    )}
                </AnimatePresence>
            </main>
        </div>
    );
}
